# Site Information
license:          "MIT"
license-url:      "https://github.com/BlackrockDigital/startbootstrap/blob/gh-pages/LICENSE"
author:           "Blackrock Digital"

# Site Settings
baseurl:          ""

# Build settings
exclude:          [node_modules]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
url:              https://startbootstrap.com
enforce_ssl:      startbootstrap.com
encoding:         UTF-8
host:             0.0.0.0
port:             9000

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - rouge

# Collections
collections:
  premium:
    output: false
  templates:
    output: true
    permalink: /template-overviews/:title/

# Pagination
paginate: 5
paginate_path: "/articles/page:num/"
